services:    
  mongodb:
    image: mongo:latest
    container_name: cs4_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cs4
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - cs4_network

  redis:
    image: redis:latest
    container_name: cs4_redis
    ports:
      - "6379:6379"
    networks:
      - cs4_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cs4_rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

networks:
  cs4_network:
    driver: bridge
