services:    
  mongodb:
    image: mongo:latest
    container_name: cs4_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cs4
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - cs4_network

  redis:
    image: redis:latest
    container_name: cs4_redis
    ports:
      - "6379:6379"
    networks:
      - cs4_network

networks:
  cs4_network:
    driver: bridge
